apiVersion: v1                  # Kubernetes API version
kind: ConfigMap                 # Kubernetes resource
metadata:
  name: app-config              # The name of the config map
  namespace: patchwork          # The name of the cluster (namespace)
data:
  BACKEND_URL: "http://backend:5001"  # The URL of the backend service