apiVersion: v1                  # Kubernetes API version 
kind: Secret                    # Kubernetes resource
metadata:
  name: app-secret              # The name of the secret
  namespace: patchwork          # The name of the cluster (namespace)
type: Opaque
stringData:
  API_KEY: "fake-skyhigh-patchwork-lab-key-2810"      # The key name referenced by Deployment